import asyncio
import logging
import math
import os
import random
import tempfile
import threading
import time
from dataclasses import dataclass, field

from fastapi import HTTPException, Request
from opentelemetry import trace
from starlette.middleware.base import BaseHTTPMiddleware

logger = logging.getLogger("api")
tracer = trace.get_tracer("chaos-engineering")


@dataclass
class ChaosState:
    """In-memory state for all 10 chaos engineering scenarios."""

    # 1. Slow Database Queries — extra delay in ms (0-5000)
    slow_db_ms: int = 0

    # 2. High Error Rate (5xx) — percentage chance 0-100
    error_rate_pct: int = 0

    # 3. Memory Leak — toggle
    memory_leak_enabled: bool = False
    _leaked_data: list = field(default_factory=list, repr=False)

    # 4. CPU Saturation — number of busy-wait threads (0-8)
    cpu_threads: int = 0
    _cpu_thread_handles: list = field(default_factory=list, repr=False)
    _cpu_stop_event: threading.Event = field(default_factory=threading.Event, repr=False)

    # 5. Downstream Dependency Timeout — sleep in seconds (0-30)
    downstream_timeout_s: int = 0

    # 6. DB Connection Pool Exhaustion — pool size (1-20, default managed externally)
    db_pool_size: int = 0  # 0 means "not active / use default"

    # 7. Log Flooding — extra log lines per request (0-1000)
    log_flood_lines: int = 0

    # 8. N+1 Query Problem — toggle
    n_plus_one_enabled: bool = False

    # 9. Disk I/O Saturation — MB to write per request (0-50)
    disk_io_mb: int = 0

    # 10. Cascading Latency (Retry Storm) — toggle
    retry_storm_enabled: bool = False

    def to_dict(self):
        return {
            "slow_db_ms": self.slow_db_ms,
            "error_rate_pct": self.error_rate_pct,
            "memory_leak_enabled": self.memory_leak_enabled,
            "memory_leak_size_mb": round(
                len(self._leaked_data) * 0.001, 2
            ),
            "cpu_threads": self.cpu_threads,
            "downstream_timeout_s": self.downstream_timeout_s,
            "db_pool_size": self.db_pool_size,
            "log_flood_lines": self.log_flood_lines,
            "n_plus_one_enabled": self.n_plus_one_enabled,
            "disk_io_mb": self.disk_io_mb,
            "retry_storm_enabled": self.retry_storm_enabled,
        }

    def reset(self):
        self.slow_db_ms = 0
        self.error_rate_pct = 0
        self.memory_leak_enabled = False
        self._leaked_data.clear()
        self.stop_cpu_threads()
        self.cpu_threads = 0
        self.downstream_timeout_s = 0
        self.db_pool_size = 0
        self.log_flood_lines = 0
        self.n_plus_one_enabled = False
        self.disk_io_mb = 0
        self.retry_storm_enabled = False

    # --- CPU saturation helpers ---

    def _cpu_busy_loop(self, stop_event: threading.Event):
        """Busy-wait loop that burns CPU until stopped."""
        while not stop_event.is_set():
            _ = math.factorial(500)

    def start_cpu_threads(self, count: int):
        self.stop_cpu_threads()
        self.cpu_threads = count
        self._cpu_stop_event.clear()
        for _ in range(count):
            t = threading.Thread(target=self._cpu_busy_loop, args=(self._cpu_stop_event,), daemon=True)
            t.start()
            self._cpu_thread_handles.append(t)

    def stop_cpu_threads(self):
        self._cpu_stop_event.set()
        for t in self._cpu_thread_handles:
            t.join(timeout=2)
        self._cpu_thread_handles.clear()
        self._cpu_stop_event.clear()

    # --- Per-request chaos application ---

    async def apply_pre_request(self):
        """Apply chaos effects that should happen before request processing."""
        with tracer.start_as_current_span("chaos.pre_request") as span:

            # 2. High Error Rate
            if self.error_rate_pct > 0:
                if random.randint(1, 100) <= self.error_rate_pct:
                    span.set_attribute("chaos.error_injected", True)
                    logger.warning("Chaos: injecting 500 error (rate=%d%%)", self.error_rate_pct)
                    raise HTTPException(status_code=500, detail="Chaos: injected server error")

            # 3. Memory Leak
            if self.memory_leak_enabled:
                chunk = "X" * 1024  # 1KB per request
                self._leaked_data.append(chunk)
                span.set_attribute("chaos.memory_leak_entries", len(self._leaked_data))

            # 7. Log Flooding
            if self.log_flood_lines > 0:
                span.set_attribute("chaos.log_flood_lines", self.log_flood_lines)
                for i in range(self.log_flood_lines):
                    logger.info(
                        "Chaos log flood line %d/%d — This is intentional noise generated by the chaos engineering module.",
                        i + 1,
                        self.log_flood_lines,
                    )

    async def apply_slow_db(self):
        """Inject latency before database calls."""
        if self.slow_db_ms > 0:
            with tracer.start_as_current_span("chaos.slow_db") as span:
                delay = self.slow_db_ms / 1000.0
                span.set_attribute("chaos.delay_ms", self.slow_db_ms)
                logger.info("Chaos: adding %dms DB delay", self.slow_db_ms)
                await asyncio.sleep(delay)

    async def apply_downstream_timeout(self):
        """Simulate a slow downstream dependency."""
        if self.downstream_timeout_s > 0:
            with tracer.start_as_current_span("chaos.downstream_timeout") as span:
                span.set_attribute("chaos.timeout_s", self.downstream_timeout_s)
                logger.info("Chaos: simulating downstream timeout of %ds", self.downstream_timeout_s)
                await asyncio.sleep(self.downstream_timeout_s)

    async def apply_disk_io(self):
        """Write temporary files to saturate disk I/O."""
        if self.disk_io_mb > 0:
            with tracer.start_as_current_span("chaos.disk_io") as span:
                span.set_attribute("chaos.disk_io_mb", self.disk_io_mb)
                logger.info("Chaos: writing %dMB to disk", self.disk_io_mb)
                data = b"0" * (1024 * 1024)  # 1MB chunk
                for _ in range(self.disk_io_mb):
                    fd, path = tempfile.mkstemp(prefix="chaos_io_")
                    try:
                        os.write(fd, data)
                    finally:
                        os.close(fd)
                        os.unlink(path)

    async def apply_retry_storm(self):
        """Simulate cascading latency via internal retry loop with backoff."""
        if self.retry_storm_enabled:
            with tracer.start_as_current_span("chaos.retry_storm") as span:
                retries = 5
                span.set_attribute("chaos.retry_count", retries)
                logger.info("Chaos: starting retry storm with %d retries", retries)
                for attempt in range(retries):
                    delay = min(0.1 * (2 ** attempt), 3.0)
                    with tracer.start_as_current_span(f"chaos.retry_attempt_{attempt}") as retry_span:
                        retry_span.set_attribute("chaos.attempt", attempt)
                        retry_span.set_attribute("chaos.backoff_s", delay)
                        await asyncio.sleep(delay)


# Global singleton
chaos_state = ChaosState()


class ChaosMiddleware(BaseHTTPMiddleware):
    """Middleware that applies chaos effects to every request."""

    async def dispatch(self, request: Request, call_next):
        # Skip chaos for the chaos control endpoints themselves
        path = request.url.path
        if path.startswith("/api/chaos") or path == "/api/health":
            return await call_next(request)

        # Apply pre-request chaos
        await chaos_state.apply_pre_request()

        # Apply per-request disk I/O
        await chaos_state.apply_disk_io()

        # Apply downstream timeout simulation
        await chaos_state.apply_downstream_timeout()

        # Apply retry storm
        await chaos_state.apply_retry_storm()

        response = await call_next(request)
        return response
